# Generated by Django 5.2.7 on 2025-11-02 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant/organization owning this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects_project",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("epic", "Epic"),
                            ("story", "Story"),
                            ("task", "Task"),
                        ],
                        db_index=True,
                        default="story",
                        help_text="Type of feature: Epic (large), Story (user story), Task (small work item)",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Priority level (higher = more important)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="open",
                        help_text="Current status (e.g., open, in-progress, done)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent feature for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="projects.feature",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant/organization owning this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "db_table": "projects_feature",
                "ordering": ["-priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="QualityAttributeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(db_index=True, default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="projects.qualityattributecategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant/organization owning this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Attribute Category",
                "verbose_name_plural": "Quality Attribute Categories",
                "db_table": "projects_qualityattributecategory",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="QualityAttributeScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the quality attribute (e.g., Performance, Security)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the quality attribute"
                    ),
                ),
                (
                    "stimulus",
                    models.TextField(
                        blank=True,
                        help_text="What triggers the concern for this quality attribute (ATAM: Stimulus)",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="How the system responds to the stimulus (ATAM: Response)",
                    ),
                ),
                (
                    "response_measure",
                    models.TextField(
                        blank=True,
                        help_text="How success is measured (ATAM: Response Measure)",
                    ),
                ),
                (
                    "environment",
                    models.TextField(
                        blank=True,
                        help_text="Context/environment where the stimulus occurs (ATAM: Environment)",
                    ),
                ),
                (
                    "scenario",
                    models.TextField(
                        blank=True,
                        help_text="Complete quality attribute scenario description",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Priority level (higher = more important)",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is a critical quality attribute",
                    ),
                ),
                (
                    "tradeoffs",
                    models.TextField(
                        blank=True,
                        help_text="Tradeoffs and architectural decisions related to this quality attribute",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for organizing quality attributes",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_attributes",
                        to="projects.qualityattributecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quality_attributes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_attributes",
                        to="projects.feature",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant/organization owning this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Attribute Scenario",
                "verbose_name_plural": "Quality Attribute Scenarios",
                "db_table": "projects_qualityattributescenario",
                "ordering": ["-priority", "-is_critical", "name"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("functional", "Functional"),
                            ("non-functional", "Non-Functional"),
                            ("constraint", "Constraint"),
                            ("business", "Business Rule"),
                        ],
                        db_index=True,
                        default="functional",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "acceptance_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Acceptance criteria or conditions of satisfaction",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Priority level (higher = more important)",
                    ),
                ),
                (
                    "is_satisfied",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this requirement has been satisfied",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="projects.feature",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant/organization owning this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
                "db_table": "projects_requirement",
                "ordering": ["-priority", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "slug"], name="projects_pr_tenant__2519ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant", "is_active"], name="projects_pr_tenant__7a3568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_by"], name="projects_pr_created_c24ee1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["project", "feature_type"],
                name="projects_fe_project_ddf158_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["project", "status"], name="projects_fe_project_b45f5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["parent"], name="projects_fe_parent__88fcfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["priority"], name="projects_fe_priorit_2abe44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityattributecategory",
            index=models.Index(
                fields=["tenant", "order"], name="projects_qu_tenant__2ce113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityattributecategory",
            index=models.Index(
                fields=["parent"], name="projects_qu_parent__b00780_idx"
            ),
        ),
                migrations.AlterUniqueTogether(
                    name="qualityattributecategory",
                    unique_together={("tenant", "name")},
                ),
        migrations.AddIndex(
            model_name="qualityattributescenario",
            index=models.Index(
                fields=["feature", "category"], name="projects_qu_feature_deceb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityattributescenario",
            index=models.Index(
                fields=["feature", "is_critical"], name="projects_qu_feature_6bc0e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityattributescenario",
            index=models.Index(
                fields=["priority"], name="projects_qu_priorit_cb3d1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(
                fields=["feature", "requirement_type"],
                name="projects_re_feature_bd0aaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(
                fields=["feature", "is_satisfied"],
                name="projects_re_feature_9ea749_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(
                fields=["priority"], name="projects_re_priorit_e7c1f2_idx"
            ),
        ),
    ]
