# Generated by Django 5.2.7 on 2025-11-02 18:08

from django.db import migrations


def create_quality_attribute_categories(apps, schema_editor):
    """Create ISO 25010 quality attribute categories for all tenants"""
    QualityAttributeCategory = apps.get_model("projects", "QualityAttributeCategory")
    Tenant = apps.get_model("users", "Tenant")

    # ISO 25010 Software Product Quality characteristics
    categories = [
        {
            "name": "Functional Suitability",
            "description": "Degree to which a product or system provides functions that meet stated and implied needs",
            "order": 10,
            "children": [
                {
                    "name": "Appropriateness",
                    "description": "Degree to which the functions facilitate the accomplishment of specified tasks and objectives",
                    "order": 11,
                },
                {
                    "name": "Accuracy",
                    "description": "Degree to which a product or system provides the correct results with the needed degree of precision",
                    "order": 12,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 13,
                },
            ],
        },
        {
            "name": "Reliability",
            "description": "Degree to which a system, product or component performs specified functions under specified conditions for a specified period of time",
            "order": 20,
            "children": [
                {
                    "name": "Availability",
                    "description": "Degree to which a system, product or component is operational and accessible when required for use",
                    "order": 21,
                },
                {
                    "name": "Fault tolerance",
                    "description": "Degree to which a system, product or component operates as intended despite the presence of hardware or software faults",
                    "order": 22,
                },
                {
                    "name": "Recoverability",
                    "description": "Degree to which, in case of an interruption or failure, a product or system can recover the data directly affected and re-establish the desired state of the system",
                    "order": 23,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 24,
                },
            ],
        },
        {
            "name": "Performance efficiency",
            "description": "Performance relative to the amount of resources used under stated conditions",
            "order": 30,
            "children": [
                {
                    "name": "Time-behaviour",
                    "description": "Degree to which the response and processing times and throughput rates of a product or system meet requirements when performing its functions",
                    "order": 31,
                },
                {
                    "name": "Resource-utilisation",
                    "description": "Degree to which the amounts and types of resources used by a product or system meet requirements when performing its functions",
                    "order": 32,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 33,
                },
            ],
        },
        {
            "name": "Operability",
            "description": "Degree to which a product or system has attributes that make it easy to operate and control",
            "order": 40,
            "children": [
                {
                    "name": "Appropriateness-recogniseability",
                    "description": "Degree to which users can recognize whether a product or system is appropriate for their needs",
                    "order": 41,
                },
                {
                    "name": "Learnability",
                    "description": "Degree to which a product or system enables the user to learn how to use it with effectiveness, efficiency, freedom from risk and satisfaction",
                    "order": 42,
                },
                {
                    "name": "Ease-of-use",
                    "description": "Degree to which a product or system enables the user to use it with effectiveness, efficiency and satisfaction",
                    "order": 43,
                },
                {
                    "name": "Helpfulness",
                    "description": "Degree to which a product or system provides helpful guidance or assistance to users",
                    "order": 44,
                },
                {
                    "name": "Attractiveness",
                    "description": "Degree to which user interfaces enable pleasing and satisfying interaction for the user",
                    "order": 45,
                },
                {
                    "name": "Technical-accessibility",
                    "description": "Degree to which a product or system can be used by people with the widest range of characteristics and capabilities to achieve a specified goal",
                    "order": 46,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 47,
                },
            ],
        },
        {
            "name": "Security",
            "description": "Degree to which a product or system protects information and data so that persons or other products or systems have the degree of data access appropriate to their types and levels of authorization",
            "order": 50,
            "children": [
                {
                    "name": "Confidentiality",
                    "description": "Degree to which a product or system ensures that data are accessible only to those authorized to have access",
                    "order": 51,
                },
                {
                    "name": "Integrity",
                    "description": "Degree to which a system, product or component prevents unauthorized access to, or modification of, computer programs or data",
                    "order": 52,
                },
                {
                    "name": "Non-repudiation",
                    "description": "Degree to which actions or events can be proven to have taken place, so that the events or actions cannot be repudiated later",
                    "order": 53,
                },
                {
                    "name": "Accountability",
                    "description": "Degree to which the actions of an entity can be traced uniquely to the entity",
                    "order": 54,
                },
                {
                    "name": "Authenticity",
                    "description": "Degree to which the identity of a subject or resource can be proved to be the one claimed",
                    "order": 55,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 56,
                },
            ],
        },
        {
            "name": "Compatibility",
            "description": "Degree to which a product, system or component can exchange information with other products, systems or components, and/or perform its required functions, while sharing the same hardware or software environment",
            "order": 60,
            "children": [
                {
                    "name": "Replace-ability",
                    "description": "Degree to which one product can replace another specified product for the same purpose in the same environment",
                    "order": 61,
                },
                {
                    "name": "Coexistence",
                    "description": "Degree to which a product can perform its required functions efficiently while sharing a common environment and resources with other products",
                    "order": 62,
                },
                {
                    "name": "Inter-operability",
                    "description": "Degree to which two or more systems, products or components can exchange information and use the information that has been exchanged",
                    "order": 63,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 64,
                },
            ],
        },
        {
            "name": "Maintainability",
            "description": "Degree of effectiveness and efficiency with which a product or system can be modified to improve it, correct it or adapt it to changes in environment, and in requirements",
            "order": 70,
            "children": [
                {
                    "name": "Modularity",
                    "description": "Degree to which a system or computer program is composed of discrete components such that a change to one component has minimal impact on other components",
                    "order": 71,
                },
                {
                    "name": "Reusability",
                    "description": "Degree to which an asset can be used in more than one system, or in building other assets",
                    "order": 72,
                },
                {
                    "name": "Analyzability",
                    "description": "Degree of effectiveness and efficiency with which it is possible to assess the impact on a product or system of an intended change to one or more of its parts",
                    "order": 73,
                },
                {
                    "name": "Changeability",
                    "description": "Degree to which a product or system can be effectively and efficiently modified without introducing defects or degrading existing product quality",
                    "order": 74,
                },
                {
                    "name": "Modification stability",
                    "description": "Degree to which a product or system avoids unexpected effects from modifications of the software",
                    "order": 75,
                },
                {
                    "name": "Testability",
                    "description": "Degree of effectiveness and efficiency with which test criteria can be established for a system, product or component and tests can be performed to determine whether those criteria have been met",
                    "order": 76,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 77,
                },
            ],
        },
        {
            "name": "Transferability",
            "description": "Degree of effectiveness and efficiency with which a system, product or component can be transferred from one hardware, software or other operational or usage environment to another",
            "order": 80,
            "children": [
                {
                    "name": "Portability",
                    "description": "Degree of effectiveness and efficiency with which a system, product or component can be transferred from one hardware, software or other operational or usage environment to another",
                    "order": 81,
                },
                {
                    "name": "Adaptability",
                    "description": "Degree to which a product or system can effectively and efficiently be adapted for different or evolving hardware, software or other operational or usage environments",
                    "order": 82,
                },
                {
                    "name": "Installability",
                    "description": "Degree of effectiveness and efficiency with which a product or system can be successfully installed and/or uninstalled in a specified environment",
                    "order": 83,
                },
                {
                    "name": "Compliance",
                    "description": "Degree of adherence to standards, conventions or regulations in laws and similar prescriptions",
                    "order": 84,
                },
            ],
        },
    ]

    # Create categories for each tenant
    for tenant in Tenant.objects.all():
        for category_data in categories:
            children = category_data.pop("children", [])
            parent_category, created = QualityAttributeCategory.objects.get_or_create(
                tenant=tenant,
                name=category_data["name"],
                defaults={
                    "description": category_data["description"],
                    "order": category_data["order"],
                },
            )

            # Create child categories
            for child_data in children:
                QualityAttributeCategory.objects.get_or_create(
                    tenant=tenant,
                    parent=parent_category,
                    name=child_data["name"],
                    defaults={
                        "description": child_data["description"],
                        "order": child_data["order"],
                    },
                )


def reverse_quality_attribute_categories(apps, schema_editor):
    """Remove seeded quality attribute categories"""
    QualityAttributeCategory = apps.get_model("projects", "QualityAttributeCategory")
    QualityAttributeCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_fix_quality_category_constraint"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_quality_attribute_categories,
            reverse_code=reverse_quality_attribute_categories,
        )
    ]
