# Generated by Django 5.2.7 on 2025-11-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="qualityattributecategory",
            unique_together={("tenant", "parent", "name")},
        ),
    ]
